### ISSUE TITLE
Hunk.__str__ and Patch.__str__ don't produce usable hunks or patches

### ISSUE THREAD

**Issue by LogicalDash** [matiasb/python-unidiff#47]
Currently, these methods join their objects' contents with an empty string, and the string returned by ``Line.__str__`` does not end with a newline. That means converting, eg., a ``Patch`` to a string results in all the lines of the patch run together with no newlines between. I can't use that. Either ``Line.__str__`` should append a newline, or the other ``__str__`` methods should join with ``'\n'`` and not ``''``.

**Comment by matiasb** [comment]
Hi! I was just taking a look to confirm, but I may be missing something because I cannot reproduce it.

Taking for example the snippet from the README:

    >>> import urllib2
    >>> from unidiff import PatchSet
    >>> diff = urllib2.urlopen('https://github.com/matiasb/python-unidiff/pull/3.diff')
    >>> encoding = diff.headers.getparam('charset')
    >>> patch = PatchSet(diff, encoding=encoding)
    >>> str(patch[0])
    'diff --git a/.gitignore b/.gitignore\nnew file mode 100644\nindex 0000000..017f622\n--- /dev/null\n+++ b/.gitignore\n@@ -0,0 +1,6 @@\n+# Python\n+*.py[cod]\n+__pycache__\n+\n+# Vim\n+*.swp\n'
    >>> print str(patch[0])
    diff --git a/.gitignore b/.gitignore
    new file mode 100644
    index 0000000..017f622
    --- /dev/null
    +++ b/.gitignore
    @@ -0,0 +1,6 @@
    +# Python
    +*.py[cod]
    +__pycache__
    +
    +# Vim
    +*.swp

`\n` are there in the string representation, and are reflected when printing the string too.
Would you provide an example of your scenario? And/or to be sure, which unidiff version are you using?

Thanks!

**Comment by LogicalDash** [comment]
I couldn't reproduce this either. I was probably stripping the lines myself or something.
