### ISSUE TITLE
Recent build breakage from 0.5.4 -> 0.5.5

### ISSUE THREAD

**Issue by Makman2** [matiasb/python-unidiff#50]
Hi :)

Recently our master branch CI failed due to the latest upgrade of `unidiff` to 0.5.5:

https://travis-ci.org/coala/coala/jobs/325392018#L754

Suddenly this occured:

```
E           unidiff.errors.UnidiffParseError: Hunk is shorter than expected
```

The test case tests how our own `Diff` class parses unified-diffs, using `unidiff`.

**Comment by Makman2** [comment]
If you need assistance with debugging and background information, please tell ;)

**Comment by matiasb** [comment]
Hi!
Reviewing the failing test, I'm wondering if you are not missing a comma here:
https://travis-ci.org/coala/coala/jobs/325392018#L772

Let me know if that's not the case and we can keep debugging.

**Comment by Makman2** [comment]
Oh good catch, wondering though why it hasn't failed before 😅 
I'll check immediately if that fixes the problem :) Thanks for looking :)

**Comment by Makman2** [comment]
Okay the comma is not severe at this place. The missing comma effectively concatenates those strings, and the expected result as well as the result under test are generated from it.

We try to create our `Diff` from such a patch using `unidiff.PatchSet`, and this is the place where it fails.
I have a little guess, that maybe a trailing `\n` is missing at the end of the diff? Maybe because of that the patches don't match. In that case that wouldn't be a bug but actually correct behaviour (although a bit more strict) :+1:

**Comment by matiasb** [comment]
> Okay the comma is not severe at this place. The missing comma effectively concatenates those strings, and the expected result as well as the result under test are generated from it.

Note that concatenating the strings there doesn't have the same effect, since you are later joining all the strings in the list with a '\n':

```
--- a/some-file.c
+++ b/some-file.c
@@ -1,3 +1,4 @@
-void main()  {
-return 09;
+void main()+{
+       return 9;
 }
```

instead of

```
--- a/some-file.c
+++ b/some-file.c
@@ -1,3 +1,4 @@
-void main()  {
-return 09;
+void main()
+{
+       return 9;
 }
```
And in fact, I think, in the first case the there is a missing line for the diff hunk. Makes sense?
(FWIW, trying to parse the first diff fails as reported, but the second one works as expected).
What seems odd is that the diff was still parsed with a previous version though.

**Comment by Makman2** [comment]
```
--- a/some-file.c
+++ b/some-file.c
@@ -1,3 +1,4 @@
-void main()  {
-return 09;
+void main()+{
+       return 9;
 }
```
Yeah exactly, however the "corrupted" line in this case is just added, so in fact we could also write there anything. What's important is that the old line that gets removed has to be the same like in the old file:
```
void main()  {
return 09
}
```
And those match.
Currently the test should just generate bad C-code (because of the `+` between `void main()` and `{`), but that's all if I see it correctly.

**Comment by matiasb** [comment]
So, summarizing: I think the parse error is correct, since the generated diff is not really ok (in the changed side there is one line missing, given the 4-length in the hunk header). I just confirmed it used not to explode before, the parser got stricter about the hunk length match the header.

I don't know the internals of your case (or why you need the malformed diff), what would be the expected behavior for you? It may be possible to introduce some parameter to disable enforcing the length, but there should be a really good reason for that (that I don't see at the moment).

**Comment by Makman2** [comment]
Ah I understand now:
```
@@ -1,3 +1,4 @@
```
This one is wrong on our side, and seems the update of `unidiff` now catches this properly :) Alright, seems I've missed that on review :3

Anyway good to know that this now works properly, maybe a test should be added here to prevent regressions?

Thanks, I really appreciate that you've taken the time to look at this ;)

**Comment by matiasb** [comment]
Great! :+1:
